language: php
php:
  - 5.5.16
  - 5.6.0
  - 7.0.0
  - 7.1.0
  - hhvm
matrix:
    allow_failures:
        - php: hhvm
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
script:
  - composer create-project --no-interaction bear/skeleton app
  - cd app
  - touch .env
  - vendor/bin/phpunit
  - php bootstrap/web.php get /
