language: php
php:
  - 5.5.0
  - 5.5.1
  - 5.5.2
  - 5.5.3
  - 5.5.4
  - 5.5.5
  - 5.5.6
  - 5.5.7
  - 5.5.8
  - 5.5.9
  - 5.5.10
  - 5.5.11
  - 5.5.12
  - 5.5.13
  - 5.5.14
  - 5.5.15
  - 5.5.16
  - 5.5.17
  - 5.5.18
  - 5.5.19
  - 5.5.20
  - 5.6.0
  - 7.0.0
  - 7.1.0
  - hhvm
matrix:
    allow_failures:
        - php: hhvm
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
script:
  - composer create-project --no-interaction bear/skeleton app
  - cd app
  - touch .env
  - vendor/bin/phpunit
  - php bootstrap/web.php get /
