language: php
sudo: required
dist: trusty
group: edge
php:
  - 5.5.29
  - 5.5
  - 5.6.0
  - 5.6
  - 7.0.0
  - 7.0
  - 7.1.0
  - 7.1
  - 7.2
  - 7.3
  - nightly
  - hhvm
  - hhvm-nightly
matrix:
    allow_failures:
        - php: hhvm
        - php: nightly
        - php: hhvm-nightly
cache:
  directories:
    - $HOME/.composer/cache
script:
  - composer self-update
  - composer create-project --no-interaction bear/skeleton app
  - cd app
  - vendor/bin/phpunit
  - php bootstrap/web.php get / || php bootstrap/page.php get /
