language: php
php:
  - 5.5
  - 5.6
  - 7
  - 7.1
  - hhvm
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
script:
  - composer create-project --no-interaction bear/skeleton app
  - cd app
  - touch .env
  - vendor/bin/phpunit
  - php bootstrap/web.php get /
