language: php
sudo: required
dist: trusty
group: edge
php:
  - 5.5.29
  - 5.5
  - 5.6.0
  - 5.6
  - 7.0.0
  - 7.0
  - 7.1.0
  - 7.1
  - 7.2.5
  - 7.2
  - 7.3.0
  - 7.3
  - 7.4.0
  - 7.4
  - nightly
matrix:
    allow_failures:
        - php: nightly
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - phpenv config-rm xdebug.ini || true
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" == "nightly" ]]; then
      php -v; composer create-project --no-interaction bear/skeleton app --ignore-platform-reqs
    else
      composer create-project --no-interaction bear/skeleton app
    fi;
  - cd app
  - vendor/bin/phpunit
  - php bootstrap/web.php get / || php bin/page.php get /
