language: php
sudo: required
dist: trusty
group: edge
php:
  - 5.5.29
  - 5.5
  - 5.6.0
  - 5.6
  - 7.0.0
  - 7.0
  - 7.1.0
  - 7.1
  - 7.2.5
  - 7.2
  - 7.3.0
  - 7.3
  - 7.4.0
  - 7.4
  - nightly
matrix:
    allow_failures:
        - php: nightly
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - phpenv config-rm xdebug.ini || true
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer validate
  - composer self-update
  - if [ "$TRAVIS_PHP_VERSION" = "nightly" ]; then
      export DEPENDENCIES="$DEPENDENCIES --ignore-platform-reqs"
    fi;
script:
  - composer create-project --no-interaction bear/skeleton app $DEPENDENCIES
  - cd app
  - vendor/bin/phpunit
  - php bootstrap/web.php get / || php bin/page.php get /
